export * from "./Home"
export * from "./About"
export * from "./Gallery"
export * from "./FoodChart"
export * from "./Contact"
export * from "./Login_popup"
export * from "./FoodBasketFinal"
export * from "./PlaceOrder"